name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Apps token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: auto issue update
        uses: actions/stale@v4
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
        with:
          stale-issue-message: "このissueは7日以上アクティビティがありません"
          close-issue-message: "このissueはstaleラベルが付与されてから7日以上アクティビティがなかったためcloseされました"
          stale-issue-label: "stale"
          days-before-issue-stale: 7
          days-before-issue-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1